---
include:
  # ======= Numpad (standalone, left PCB) =======
  - board: zitaotech_sofle_numpad

  - board: zitaotech_sofle_numpad
    shield: settings_reset


  # ======= Left (displays, pointing) =======
  - board: zitaotech_sofle_left
    shield: lpm_view;left_bbtrackball

  - board: zitaotech_sofle_left
    shield: lpm_view;left_bbtrackpad



  # ======= Left settings reset =======
  - board: zitaotech_sofle_left
    shield: lpm_view;left_bbtrackball;settings_reset
  - board: zitaotech_sofle_left
    shield: lpm_view;left_bbtrackpad;settings_reset


#  ====== Right - commented out for numpad project ======
#  - board: zitaotech_sofle_right
#    shield: lpm_view;right_trackpoint
#  - board: zitaotech_sofle_right
#    shield: lpm_view;right_trackpoint;settings_reset
