---
  # ====== Left (Numpad / standalone) ======
  - board: zitaotech_sofle_left

  - board: zitaotech_sofle_left
    shield: lpm_view;left_bbtrackball

  - board: zitaotech_sofle_left
    shield: lpm_view;left_bbtrackpad

  - board: zitaotech_sofle_left
    shield: settings_reset

  - board: zitaotech_sofle_left
    shield: lpm_view;left_bbtrackball;settings_reset
  - board: zitaotech_sofle_left
    shield: lpm_view;left_bbtrackpad;settings_reset


#  ====== Right — commented out ======
#  - board: zitaotech_sofle_right
#    shield: lpm_view;right_trackpoint
#  - board: zitaotech_sofle_right
#    shield: lpm_view;right_trackpoint;settings_reset
